version: '3.8'

services:
	mysql:
		container_name: MySQL
		ports:
			- '3306:3306'
		restart: always
		volumes:
			- /db_data:/var/lib/mysql
		environment:
			MYSQL_ROOT_PASSWORD: apostolos
			MYSQL_DATABASE: wordpress
			MYSQL_USER: cloud
			MYSQL_PASSWORD: apostolos
		deploy:
			resources:
				limits:
					cpus: '0.10'
					memory: 500M
				reservations:
					cpus: '0.05'
					memory: 50M
			networks:
				- vlab_network

volumes:
	data:
		driver: local
